apiVersion: v1
kind: Service
metadata:
  name: single-price-grid-component
  namespace: default
spec:
  selector:
    app: single-price-grid-component-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
